/*

 MODESELECTA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Thomas Wiltshire\Documents\GitHub\BugSprayerGB\Gbtd-Gbmb\gameselect.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __ModeSelectA_h_INCLUDE
#define __ModeSelectA_h_INCLUDE

#define m_caModeSelectAWidth 20
#define m_caModeSelectAHeight 18
#define m_caModeSelectABank 0

extern const unsigned char m_caModeSelectA[];

#endif

/* End of MODESELECTA.H */
