/*

 SPLASHMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : splashscreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __SplashMap_h_INCLUDE
#define __SplashMap_h_INCLUDE

#define m_caSplashMapWidth 20
#define m_caSplashMapHeight 18
#define m_caSplashMapBank 0

extern const unsigned char m_caSplashMap[];

#endif

/* End of SPLASHMAP.H */
