/*

 STARTSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Thomas Wiltshire\Documents\GitHub\DiggingSimulator1989\Gbtd-Gbmb\startscreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __StartScreen_h_INCLUDE
#define __StartScreen_h_INCLUDE

#define m_caStartScreenWidth 20
#define m_caStartScreenHeight 18
#define m_caStartScreenBank 0

extern const unsigned char m_caStartScreen[];

#endif

/* End of STARTSCREEN.H */
